# Generated by Django 5.2.4 on 2025-07-18 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITRE', models.CharField(max_length=50)),
                ('DATE_DE_SORTIE', models.DateTimeField(auto_now_add=True)),
                ('NOTE_PERSONNELLE', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
