# Generated by Django 5.2.4 on 2025-07-25 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('plateforme', models.CharField(choices=[('PC', 'PC'), ('PS', 'Playstation'), ('XBOX', 'Xbox'), ('SWITCH', 'Switch'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('genres', models.CharField(choices=[('ACTION', 'Action'), ('SPORT', 'Sport'), ('AVENTURE', 'Aventure'), ('RPG', 'RPG'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('date_de_sortie', models.DateTimeField(blank=True, null=True)),
                ('note_personnelle', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('jaquette', models.ImageField(blank=True, null=True, upload_to='jaquettes/')),
            ],
        ),
    ]
