# Generated by Django 5.2.4 on 2025-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0002_alter_jeuvideo_genres_alter_jeuvideo_plateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeuvideo',
            name='genres',
            field=models.CharField(choices=[('ACTION', 'Action'), ('AVENTURE', 'Aventure'), ('RPG', 'RPG'), ('STRATEGIE', 'Stratégie'), ('SIMULATION', 'Simulation'), ('SPORT', 'Sport'), ('COURSE', 'Course'), ('PUZZLE', 'Puzzle / Réflexion'), ('FPS', 'FPS (Shooter)'), ('HORREUR', 'Horreur'), ('PARTY', 'Party Game'), ('MUSIQUE', 'Musique / Rythme'), ('MMO', 'MMORPG'), ('SANDBOX', 'Sandbox / Construction'), ('EDUCATIF', 'Éducatif'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jeuvideo',
            name='plateforme',
            field=models.CharField(choices=[('PC', 'PC'), ('PS', 'Playstation'), ('XBOX', 'Xbox Series'), ('X360', 'Xbox 360'), ('SWITCH', 'Nintendo Switch'), ('WII', 'Nintendo Wii'), ('DS', 'Nintendo DS'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('MAC', 'Mac'), ('LINUX', 'Linux'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15),
        ),
    ]
